[package]
name = "rc_network"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.6.0"
libc = "0.2.0"
#steamworks = "0.7.0"
simplelog = "0.7.5"
serde = "1.0.126"
log = "0.4.14"
chrono = "0.4.19"

[lib]
crate-type = ["staticlib"]

[profile.dev]
opt-level = 3
